apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filterapartments-chart.fullname" . }}-db
  labels:
    {{- include "filterapartments-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "filterapartments-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "filterapartments-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "filterapartments"
            - name: POSTGRES_USER
              value: "filterapartments"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filter-apartments
                  key: postgres_password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "filterapartments-chart.fullname" . }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "filterapartments-chart.fullname" . }}-db
  labels:
    {{- include "filterapartments-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "filterapartments-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filterapartments-chart.fullname" . }}-db-pvc
  labels:
    {{- include "filterapartments-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
