# Default values for filterapartments-chart.
replicaCount: 1

image:
  repository: 741769145503.dkr.ecr.eu-central-1.amazonaws.com/filter-apartments
  pullPolicy: IfNotPresent
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Persistent Volume Claim for bot session
persistence:
  enabled: true
  storageClass: "standard" # Using default storage class
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}

# Volume mounts for the main container
volumeMounts:
  - name: bot-session
    mountPath: /app/session

# Application configuration is managed via secrets

# Session configuration
session:
  path: /app/session/bot
